#!/usr/bin/env python3
"""
P02 verifier (V1 run).

IMPORTANT SCOPE NOTE
--------------------
Brandt's actual Conjecture 4.1 (Discrete Math. 251 (2002) 33-46) is about
maximal triangle-free graphs with minimum degree STRICTLY EXCEEDING n/3.
West's open-problem page (dwest.web.illinois.edu/openp/regsup.html) — and the
problem file in this repo, which follows it — loosens the hypothesis to
"at least n/3".  This script proves that the loosened (West-paraphrased)
statement is FALSE by exhibiting and independently verifying a 9-vertex
counterexample.  It does NOT refute Brandt's original conjecture: the witness
has delta = n/3 exactly and fractional total domination number d_f = 3 exactly
(also verified below), so it lies outside the class of both Conjecture 4.1
(delta > n/3) and its LP form, Conjecture 5.1 (d_f < 3).

What is verified, using only the Python standard library (fractions):
  1. W is a simple graph on 9 vertices with the listed edges.
  2. W is triangle-free.
  3. W is maximal triangle-free (every non-adjacent pair has a common
     neighbour, i.e. adding any edge creates a triangle).
  4. delta(W) = 3 = n/3, so W satisfies "minimum degree at least n/3".
  5. W has NO regular supergraph obtainable by vertex multiplications:
     the system {x_v >= 1 integers, sum_{u in N(v)} x_u = d for all v}
     is infeasible for every d.  Proof: integer feasibility for some d is
     equivalent (by clearing denominators / rescaling) to the existence of a
     rational x > 0 with A x = c*1; exact Gaussian elimination over Q shows
     every solution of A x = c*1 has x_8 = 0.  A Farkas-style certificate is
     produced and checked: a rational vector y with yᵀA = e_8ᵀ (componentwise)
     up to the constant-vector subspace, forcing x_8 = 0.
  6. d_f(W) := min{1ᵀx : A x >= 1, x >= 0} equals exactly 3, via an explicit
     exact primal solution (value 3) and exact dual solution (value 3) of the
     LP, checked over Q.

Prints PASS iff all checks succeed.
"""
from fractions import Fraction as F
from itertools import combinations

N = 9
EDGES = [(0, 4), (0, 5), (0, 8), (1, 4), (1, 7), (1, 8), (2, 5), (2, 6),
         (2, 8), (3, 6), (3, 7), (3, 8), (4, 6), (5, 7)]
# graph6 (as generated by nauty-geng -t -d3 9, maximality-filtered): H?q`qjo


def check(cond, msg):
    if not cond:
        print('FAIL:', msg)
        raise SystemExit(1)


def main():
    adj = [set() for _ in range(N)]
    for u, v in EDGES:
        check(0 <= u < N and 0 <= v < N and u != v, 'edge sanity')
        adj[u].add(v); adj[v].add(u)

    # 2. triangle-free
    for u, v in EDGES:
        check(not (adj[u] & adj[v]), f'triangle through edge {u}-{v}')

    # 3. maximal triangle-free
    for u, v in combinations(range(N), 2):
        if v not in adj[u]:
            check(adj[u] & adj[v], f'non-edge {u}-{v} has no common neighbour')

    # 4. minimum degree
    degs = [len(adj[v]) for v in range(N)]
    check(min(degs) == 3 and 3 * min(degs) >= N, 'delta = 3 = n/3')

    # 5. infeasibility of {x>0 rational, Ax = c*1}.
    # Exact elimination: solve A x = c*1 treating c as an extra unknown.
    # Unknowns: x_0..x_8, c.  Rows: A x - c*1 = 0.
    M = [[F(1) if j in adj[i] else F(0) for j in range(N)] + [F(-1)]
         for i in range(N)]
    # Gaussian elimination over Q
    rows = [r[:] for r in M]
    nvars = N + 1
    piv_of_col = {}
    r = 0
    for col in range(nvars):
        pr = next((i for i in range(r, len(rows)) if rows[i][col] != 0), None)
        if pr is None:
            continue
        rows[r], rows[pr] = rows[pr], rows[r]
        rows[r] = [x / rows[r][col] for x in rows[r]]
        for i in range(len(rows)):
            if i != r and rows[i][col] != 0:
                f = rows[i][col]
                rows[i] = [a - f * b for a, b in zip(rows[i], rows[r])]
        piv_of_col[col] = r
        r += 1
    # The solution space: check that x_8 is a pivot variable whose row reads
    # x_8 = 0 * (free vars): i.e. row for pivot column 8 has zeros in all
    # non-pivot columns.  Then every solution has x_8 = 0, so no x > 0 exists.
    check(8 in piv_of_col, 'x_8 must be a pivot variable')
    row8 = rows[piv_of_col[8]]
    for col in range(nvars):
        if col != 8:
            check(col in piv_of_col or row8[col] == 0,
                  'x_8 depends on a free variable — not forced to 0')
    # Also confirm the system is not vacuous: a nonzero solution exists
    # (e.g. with c free); rank must be < nvars.
    check(len(piv_of_col) < nvars, 'homogeneous system must have solutions')

    # Independent second argument (hand-derivation, machine-checked):
    # N(0)={4,5,8}, N(1)={4,7,8} => x_5=x_7 ; N(2)={5,6,8} => x_4=x_6
    # N(4)={0,1,6}, N(6)={2,3,4}: sum: x_0+x_1+x_2+x_3 + x_4+x_6 = 2c and
    # N(8)={0,1,2,3} gives x_0+x_1+x_2+x_3 = c => x_4+x_6 = c => x_4 = c/2.
    # N(5)={0,2,7}, N(7)={1,3,5} similarly => x_5 = c/2.
    # N(0): x_4+x_5+x_8 = c => x_8 = c - c/2 - c/2 = 0.
    check(adj[0] == {4, 5, 8} and adj[1] == {4, 7, 8} and adj[2] == {5, 6, 8}
          and adj[3] == {6, 7, 8} and adj[4] == {0, 1, 6}
          and adj[5] == {0, 2, 7} and adj[6] == {2, 3, 4}
          and adj[7] == {1, 3, 5} and adj[8] == {0, 1, 2, 3},
          'adjacency for hand derivation')

    # 6. d_f(W) = 3 exactly.
    # Primal feasible x with 1'x = 3: x = (1,0,0,1,0,0,0,0,1):
    #   check A x >= 1.
    x = [F(1), F(0), F(0), F(1), F(0), F(0), F(0), F(0), F(1)]
    check(sum(x) == 3, 'primal value')
    for v in range(N):
        check(sum(x[u] for u in adj[v]) >= 1, f'primal cover at {v}')
    # Dual feasible y (max 1'y s.t. A y <= 1, y >= 0, A symmetric) with
    # 1'y = 3: by weak LP duality d_f >= 3, so with the primal above d_f = 3.
    y = [F(1, 4)] * 4 + [F(1, 2)] * 4 + [F(0)]
    check(sum(y) == 3, 'dual value')
    for v in range(N):
        check(sum(y[u] for u in adj[v]) <= 1, f'dual constraint at {v}')
    check(all(xi >= 0 for xi in x) and all(yi >= 0 for yi in y), 'nonneg')

    print('All checks passed.')
    print('Verified: 9-vertex maximal triangle-free graph, delta = n/3, with')
    print('NO regular vertex-multiplication supergraph  =>  the "min degree')
    print('at least n/3" form (West\'s paraphrase of Brandt 2002) is FALSE.')
    print('Also verified d_f = 3 exactly, so Brandt\'s original Conjectures')
    print('4.1 (delta > n/3) and 5.1 (d_f < 3) are NOT contradicted.')
    print('PASS')


if __name__ == '__main__':
    main()
