#!/usr/bin/env python3
"""
Independent reconstruction + certification of the record Folkman graph G_786
behind the known upper bound  Fe(3,3;4) <= 786.

Source: A. Lange, S. Radziszowski, X. Xu,
"Use of MAX-CUT for Ramsey Arrowing of Triangles", arXiv:1207.3750,
Theorem 5 (th:786) and surrounding text.

Definition (verbatim from the paper):
  L(n,s): circulant on Z_n with connection set S = { s^i mod n : i>=0 },
          provided (-1 mod n) in S.  {u,v} in E iff (u-v mod n) in S.
  G_786 = L(785,53) plus ONE new vertex (index 785) joined to the 60
          listed vertices below.

Paper's claimed structural facts (the checkable ones):
  - G_786 is K4-free
  - 61290 edges
  - 428881 triangles   (=> 2*t_tri = 857762, the value used in the arrowing proof)

Arrowing G_786 -> (3,3) itself was established in the paper via a MAX-CUT SDP
upper bound (857753 < 857762 = 2*t_tri), NOT via a SAT/DRAT certificate, so we
do NOT re-certify arrowing here; we independently reproduce the exact graph and
its structural claims (which are the machine-checkable content).
"""
import itertools
import sys

N = 785
S_GEN = 53

# The 60 neighbours of the extra vertex, exactly as printed in the paper.
EXTRA_NEIGHBORS = [
    0, 1, 3, 4, 6, 7, 9, 10, 12, 13, 15, 16,
    18, 19, 21, 22, 24, 25, 27, 28, 30, 31, 33, 34,
    36, 37, 39, 40, 42, 43, 45, 46, 48, 49, 51, 52,
    54, 55, 57, 58, 60, 61, 63, 66, 69, 201, 204, 207,
    210, 213, 216, 219, 222, 225, 416, 419, 422, 630, 642, 645,
]


def connection_set(n, s):
    """S = { s^i mod n }, the multiplicative subgroup generated by s."""
    conn = set()
    x = 1 % n
    while True:
        conn.add(x)
        x = (x * s) % n
        if x == 1 % n:
            break
    return conn


def build():
    S = connection_set(N, S_GEN)
    assert (-1) % N in S, "L(n,s) requires -1 mod n in S (undirected)"
    # circulant adjacency
    adj = [set() for _ in range(N + 1)]  # vertex N is the extra vertex
    for u in range(N):
        for d in S:
            v = (u + d) % N
            if v != u:
                adj[u].add(v)
                adj[v].add(u)
    # extra vertex
    extra = N
    for v in EXTRA_NEIGHBORS:
        adj[extra].add(v)
        adj[v].add(extra)
    return adj, S


def count_edges(adj):
    return sum(len(a) for a in adj) // 2


def count_triangles(adj):
    t = 0
    for v in range(len(adj)):
        nb = adj[v]
        for a, b in itertools.combinations(nb, 2):
            if a < v or b < v:  # count each triangle once (v smallest)
                continue
            if b in adj[a]:
                t += 1
    return t


def is_k4_free(adj):
    """G is K4-free  <=>  every neighbourhood induces a triangle-free graph.
    For each vertex v, check no edge {a,b} within N(v) has a common
    neighbour c that is also in N(v) (that would be a K4 on v,a,b,c)."""
    n = len(adj)
    for v in range(n):
        nb = adj[v]
        # find a triangle inside the neighbourhood of v
        for a in nb:
            common = adj[a] & nb
            for b in common:
                if b <= a:
                    continue
                # a,b adjacent and both in N(v); need a common neighbour c in N(v)
                if (adj[a] & adj[b] & nb):
                    # v,a,b + that c is a K4
                    c = next(iter(adj[a] & adj[b] & nb))
                    return False, (v, a, b, c)
    return True, None


def main():
    adj, S = build()
    n_vertices = len(adj)
    e = count_edges(adj)
    print(f"L(785,53): |S|={len(S)} (degree of circulant part)")
    print(f"G_786: vertices={n_vertices} edges={e}")
    assert n_vertices == 786, n_vertices
    assert e == 61290, f"edges {e} != 61290"

    t = count_triangles(adj)
    print(f"triangles={t}  (2*t_tri={2*t})")
    assert t == 428881, f"triangles {t} != 428881"
    assert 2 * t == 857762

    k4free, witness = is_k4_free(adj)
    print(f"K4-free={k4free}" + ("" if k4free else f" (K4 at {witness})"))
    assert k4free, f"NOT K4-free: {witness}"

    print()
    print("CERTIFIED (independent reconstruction matches the paper exactly):")
    print("  vertices = 786")
    print("  edges    = 61290   [paper: 61290]")
    print("  triangles= 428881  [paper: 428881]")
    print("  2*t_tri  = 857762  [paper: 857762]")
    print("  K4-free  = True    [paper: 'still K4-free']")
    print("  (arrowing G_786 -> (3,3) rests on the paper's MAX-CUT SDP bound")
    print("   857753 < 857762, not reproduced here; structural claims verified.)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
