#!/usr/bin/env python3
"""Independent structural verifier for the record graph G_786.

This intentionally does not import build_g786.py for construction or counting.
The import at the end is only an edge-set cross-check against the primary
reconstruction.
"""

import itertools
import sys
from pathlib import Path


N_CIRC = 785
EXTRA = 785
GENERATOR = 53
EXTRA_NEIGHBORS = (
    0, 1, 3, 4, 6, 7, 9, 10, 12, 13, 15, 16,
    18, 19, 21, 22, 24, 25, 27, 28, 30, 31, 33, 34,
    36, 37, 39, 40, 42, 43, 45, 46, 48, 49, 51, 52,
    54, 55, 57, 58, 60, 61, 63, 66, 69, 201, 204, 207,
    210, 213, 216, 219, 222, 225, 416, 419, 422, 630, 642, 645,
)


def powers_modulo(n, generator):
    """Return the subgroup generated by generator by iterating powers."""
    values = []
    current = 1
    while current not in values:
        values.append(current)
        current = (current * generator) % n
    return frozenset(values)


def build_locally():
    connection = powers_modulo(N_CIRC, GENERATOR)
    assert len(connection) == 156
    assert connection == frozenset((-d) % N_CIRC for d in connection)

    # Build canonical edges directly from pair differences, rather than by
    # mutating adjacency sets for every directed connection.
    edges = {
        (u, v)
        for u, v in itertools.combinations(range(N_CIRC), 2)
        if (v - u) % N_CIRC in connection
    }
    assert len(edges) == N_CIRC * len(connection) // 2 == 61230
    assert len(EXTRA_NEIGHBORS) == 60
    assert len(set(EXTRA_NEIGHBORS)) == 60
    assert all(0 <= v < N_CIRC for v in EXTRA_NEIGHBORS)
    edges.update((min(EXTRA, v), max(EXTRA, v)) for v in EXTRA_NEIGHBORS)

    adjacency = [set() for _ in range(N_CIRC + 1)]
    for u, v in edges:
        adjacency[u].add(v)
        adjacency[v].add(u)
    return adjacency, edges, connection


def enumerate_triangles(adjacency):
    triangles = []
    for a in range(len(adjacency)):
        larger = [b for b in adjacency[a] if b > a]
        for b, c in itertools.combinations(larger, 2):
            if c in adjacency[b]:
                triangles.append((a, b, c))
    return triangles


def verify_k4_free(adjacency, triangles):
    # A 4-clique exists exactly when one triangle has a common neighbour.
    for a, b, c in triangles:
        common = adjacency[a] & adjacency[b] & adjacency[c]
        if common:
            return False, (a, b, c, min(common))
    return True, None


def edge_set(adjacency):
    return {
        (u, v)
        for u in range(len(adjacency))
        for v in adjacency[u]
        if u < v
    }


def main():
    adjacency, edges, connection = build_locally()
    assert len(adjacency) == 786
    assert len(edges) == 61290
    triangles = enumerate_triangles(adjacency)
    assert len(triangles) == 428881
    k4_free, witness = verify_k4_free(adjacency, triangles)
    assert k4_free, f"K4 witness: {witness}"

    # Cross-check only after all local construction and structural checks.
    root = Path(__file__).resolve().parent
    sys.path.insert(0, str(root))
    import build_g786

    primary_adjacency, _ = build_g786.build()
    primary_edges = {
        (u, v)
        for u in range(len(primary_adjacency))
        for v in primary_adjacency[u]
        if u < v
    }
    assert edges == primary_edges

    print(
        f"independent G_786 verifier: connection_size={len(connection)} "
        f"vertices={len(adjacency)} edges={len(edges)} "
        f"triangles={len(triangles)} 2*t_tri={2 * len(triangles)} "
        f"K4-free={k4_free}"
    )
    print("PASS: independent structural reconstruction and edge-set cross-check agree")


if __name__ == "__main__":
    main()
