#!/usr/bin/env python3
"""Mechanized nonexistence battery over the open CW(n,k) cells, n<=200.

For each open cell:
  1. d = gcd(n,k), m = n/d.  If gcd(m,k)=1, find McFarland d-multipliers
     t (Theorem 4.1).  (d=1 and k a prime power reduces to Theorem 2.4.)
  2. Pick t generating the largest multiplier subgroup; exhaust all
     ICW_d(m,k) fixed by t (up to translation+sign, standard reduction).
  3. Report the solution count.  Count 0  =>  no CW(n,k)
     (conditional on the multiplier/fixed-translate step, as in AGZ).
Also prints self-conjugacy info used by Lander's Theorem 2.2.
"""
import sys
import time
from math import gcd
from cwm_tools import (factorize, mult_order, is_self_conjugate,
                       mcfarland_multipliers, icw_exhaust)

OPEN_CELLS = [
    # (n, k) open in cwm.json commit 5b3d729 (2026-04-24), n<=200, s<=10,
    # minus the five cells with verified witnesses recovered from dataset
    # history (96,36),(146,64),(155,25),(165,25),(186,25) - see
    # solutions/P11/witnesses.json
    (105, 36), (112, 36), (117, 36), (140, 36), (180, 36), (195, 36),
    # (120,49) and (192,49) have d=1: the "ICW" exhaust is the full CW
    # search over Z_n orbits of 7; done separately in C (exhaust120.c)
    (140, 64), (180, 64), (182, 64), (196, 64),
    (132, 81), (156, 81), (195, 81), (198, 81),
    (112, 100), (120, 100), (155, 100), (156, 100), (165, 100),
    (182, 100), (195, 100),
]


def analyze(n, k, run_exhaust=True, max_orbits=40):
    import math
    s = int(math.isqrt(k))
    assert s * s == k
    d = gcd(n, k)
    m = n // d
    info = {"n": n, "k": k, "s": s, "d": d, "m": m}
    if gcd(m, k) != 1:
        info["note"] = f"gcd(m={m},k)={gcd(m,k)}>1: no McFarland multiplier"
        return info
    ts = mcfarland_multipliers(m, k)
    nontriv = [t for t in ts if t % m != 1]
    info["multipliers"] = ts
    info["sc"] = {p: [q for q in divisors(m) if q > 2 and
                      is_self_conjugate(p, q)]
                  for p in factorize(k)}
    if not nontriv:
        info["note"] = "trivial multiplier group only; exhaust infeasible"
        return info
    # generator of the whole multiplier group: the intersection subgroup is
    # cyclic iff generated by one element; try all, keep max order
    t = max(nontriv, key=lambda x: mult_order(x, m))
    info["t"] = t
    info["ord_t"] = mult_order(t, m)
    if run_exhaust:
        t0 = time.time()
        sols, orbs = icw_exhaust(m, k, s, d, t)
        info["n_orbits"] = len(orbs)
        info["n_icw"] = len(sols)
        info["secs"] = round(time.time() - t0, 1)
    return info


def divisors(m):
    return [q for q in range(1, m + 1) if m % q == 0]


def main():
    only = None
    if len(sys.argv) > 1:
        only = (int(sys.argv[1]), int(sys.argv[2]))
    for (n, k) in OPEN_CELLS:
        if only and (n, k) != only:
            continue
        info = analyze(n, k)
        print(info, flush=True)


if __name__ == "__main__":
    main()
