"""Toolbox for mechanized CW(n,k) nonexistence tests (P11, variant V5).

Implements, from Arasu-Gordon-Zhang (Cryptogr. Commun. 2021, arXiv:1908.08447):
  - Theorem 2.2 (Lander): self-conjugacy => trivial intersection numbers
  - Theorem 2.4: prime-power weight multiplier theorem
  - Theorem 4.1 (McFarland): d-multipliers for contracted ICW_d(m,k)
  - Lemma 2.5: intersection-number moment equations
  - Algorithm 1-style orbit exhaust for ICW_d(m,k) fixed by a multiplier
"""
from math import gcd
from functools import lru_cache


def factorize(n):
    f = {}
    d = 2
    while d * d <= n:
        while n % d == 0:
            f[d] = f.get(d, 0) + 1
            n //= d
        d += 1
    if n > 1:
        f[n] = f.get(n, 0) + 1
    return f


def mult_order(t, m):
    assert gcd(t, m) == 1
    o, x = 1, t % m
    while x != 1:
        x = x * t % m
        o += 1
    return o


def is_self_conjugate(p, m):
    """p self-conjugate mod m: exists i with p^i = -1 mod v(m),
    v(m) = largest divisor of m coprime to p."""
    v = m
    while v % p == 0:
        v //= p
    if v <= 2:
        return True
    x = p % v
    seen = set()
    while x not in seen:
        if x == v - 1:
            return True
        seen.add(x)
        x = x * p % v
    return False


def orbits(m, t):
    """Orbits of x -> t*x on Z_m."""
    done = [False] * m
    out = []
    for x in range(m):
        if done[x]:
            continue
        orb = []
        y = x
        while not done[y]:
            done[y] = True
            orb.append(y)
            y = y * t % m
        out.append(sorted(orb))
    return out


def cyclic_subgroup(t, m):
    g, x = {1 % m}, t % m
    while x not in g:
        g.add(x)
        x = x * t % m
    return g


def mcfarland_multipliers(m, k):
    """All t in Z_m^* that are simultaneously a power of every prime
    divisor of k mod m (Theorem 4.1). Requires gcd(m,k)=1."""
    assert gcd(m, k) == 1
    groups = [cyclic_subgroup(p, m) for p in factorize(k)]
    inter = set.intersection(*groups)
    return sorted(inter)


def multiplier_group(m, k):
    """Group generated by all McFarland multipliers (it is <t> for each
    t in the intersection subgroup; the intersection is itself a group)."""
    return mcfarland_multipliers(m, k)


def icw_exhaust(m, k, s, d, t, max_solutions=None, require_fixed=True,
                progress=None):
    """Exhaust all B in Z[Z_m], coefficients in [-d, d], fixed by x->t*x,
    with B(1) = s and B B^(-1) = k*delta_0.  Returns list of coefficient
    vectors (tuples of length m).

    Nonexistence of any such B, PLUS validity of the multiplier/fixed-
    translate assumption, implies no ICW_d(m,k) and hence no CW(d*m,k)
    when d = gcd(n,k), m = n/d.
    """
    orbs = orbits(m, t)
    # order orbits large->small for stronger sum-of-squares pruning
    orbs.sort(key=len, reverse=True)
    u = len(orbs)
    sizes = [len(o) for o in orbs]
    sols = []

    # incremental autocorrelation bookkeeping is done at the leaf; the
    # moment equations prune the tree hard enough for the sizes we use.
    def full_check(coef):
        a = [0] * m
        for c, orb in zip(coef, orbs):
            for x in orb:
                a[x] += c
        for g in range(1, m):
            if sum(a[i] * a[(i + g) % m] for i in range(m)) != 0:
                return None
        if sum(v * v for v in a) != k:
            return None
        return tuple(a)

    # DFS over orbit coefficients
    def rec(i, rsum, rsq):
        if max_solutions is not None and len(sols) >= max_solutions:
            return
        if rsq > k:
            return
        if i == u:
            if rsum == s and rsq == k:
                a = full_check(coef)
                if a is not None:
                    sols.append(a)
            return
        # bound: remaining orbits can change sum by at most d*sum(sizes[i:])
        rem = sum(sizes[i:])
        if abs(s - rsum) > d * rem:
            return
        for c in range(-d, d + 1):
            coef[i] = c
            rec(i + 1, rsum + c * sizes[i], rsq + c * c * sizes[i])
        coef[i] = 0

    coef = [0] * u
    rec(0, 0, 0)
    return sols, orbs
