"""Type-M constructions over rings other than Parts' Q(sqrt33).

Parts' lattice is z = (a + b*sqrt(33) + i(c*sqrt3 + d*sqrt11))/12, and |z| = 1
iff a^2 + 33b^2 + 3c^2 + 11d^2 = 144 and ab + cd = 0.  Nothing forces (p, q, m)
= (3, 11, 12): the same algebra works for any squarefree p < q and any m, with

    |z|^2 = [ (a^2 + pq b^2 + p c^2 + q d^2) + 2(ab + cd) sqrt(pq) ] / m^2,

so the unit vectors are the integer solutions of a^2 + pq b^2 + p c^2 + q d^2 =
m^2, ab + cd = 0.  The point set generated by those vectors is a lattice, unit
distance is membership of the difference in that solution set (exact integer
test), and the type-M union is P u omega_t P.

This is the one axis the whole run has never touched: E34 varied the base inside
Parts' ring, the omega_t survey varied the rotation, but the *ring* was always
his.  Floats are a prefilter for the scan only; a hit is re-verified exactly.

Env: MRANGE, PQ, TS, NLAYER, RS, NMAX, CAP, PART/NPART.
"""
import itertools
import math
import os
import pickle
import subprocess
import time

import numpy as np

from sat import color_cnf, write_cnf, KISSAT

MMAX = int(os.environ.get('MMAX', '16'))
PQMAX = int(os.environ.get('PQMAX', '15'))
TS = [int(x) for x in os.environ.get('TS', '2,3,4,5,6,7,8,10,12,16').split(',')]
NLAYER = int(os.environ.get('NLAYER', '3'))
RS = [float(x) for x in os.environ.get('RS', '2.0').split(',')]
NMAX = int(os.environ.get('NMAX', '9000'))
BMAX = int(os.environ.get('BMAX', str(NMAX)))
CAP = int(os.environ.get('CAP', '120'))
PART = int(os.environ.get('PART', '0'))
NPART = int(os.environ.get('NPART', '1'))
UMIN = int(os.environ.get('UMIN', '8'))


def squarefree(n):
    return all(n % (k * k) for k in range(2, int(n ** 0.5) + 1))


def units(p, q, m):
    """All (a,b,c,d) with a^2+pq b^2+p c^2+q d^2 = m^2 and ab+cd = 0."""
    M = m * m
    out = []
    ba = int(math.isqrt(M))
    bb = int(math.isqrt(M // (p * q)))
    bc = int(math.isqrt(M // p))
    bd = int(math.isqrt(M // q))
    for a in range(-ba, ba + 1):
        ra = M - a * a
        if ra < 0:
            continue
        for b in range(-bb, bb + 1):
            rb = ra - p * q * b * b
            if rb < 0:
                continue
            for c in range(-bc, bc + 1):
                rc = rb - p * c * c
                if rc < 0:
                    continue
                if rc % q:
                    continue
                d2 = rc // q
                d = int(math.isqrt(d2))
                if d * d != d2:
                    continue
                for dd in ({d, -d} if d else {0}):
                    if a * b + c * dd == 0:
                        out.append((a, b, c, dd))
    return sorted(set(out))


def to_z(v, p, q, m):
    a, b, c, d = v
    return complex(a + b * math.sqrt(p * q),
                   c * math.sqrt(p) + d * math.sqrt(q)) / m


def build(p, q, m, U, r, layers):
    cur = {(0, 0, 0, 0)}
    for _ in range(layers):
        nxt = set()
        for x in cur:
            for u in U:
                y = tuple(x[i] + u[i] for i in range(4))
                if abs(to_z(y, p, q, m)) <= r + 1e-9:
                    nxt.add(y)
        cur |= nxt
        if len(cur) > BMAX:
            break
    return sorted(cur)


def colorable(n, E, tag):
    nvars, cls = color_cnf(n, E, 4)
    cnf = f'/tmp/gs_{tag}_{os.getpid()}.cnf'
    write_cnf(cnf, nvars, cls)
    try:
        res = subprocess.run([KISSAT, f'--time={CAP}', cnf],
                             capture_output=True, text=True)
        if 's UNSATISFIABLE' in res.stdout:
            return False
        if 's SATISFIABLE' in res.stdout:
            return True
        return None
    finally:
        if os.path.exists(cnf):
            os.unlink(cnf)


def edges_of(Z):
    E = []
    for i0 in range(0, len(Z), 512):
        D = np.abs(Z[i0:i0 + 512, None] - Z[None, :])
        ii, jj = np.nonzero(np.abs(D - 1.0) < 1e-9)
        for i, j in zip(ii, jj):
            i, j = i0 + int(i), int(j)
            if i < j:
                E.append((i, j))
    return E


def main():
    cands = []
    for p, q in itertools.combinations(
            [n for n in range(1, PQMAX + 1) if squarefree(n)], 2):
        for m in range(2, MMAX + 1):
            cands.append((p, q, m))
    k = -1
    for (p, q, m) in cands:
        U = units(p, q, m)
        U = [u for u in U if any(u)]
        if len(U) < UMIN:
            continue
        k += 1
        if k % NPART != PART:
            continue
        print(f'p={p} q={q} m={m}: {len(U)} unit vectors', flush=True)
        for r in RS:
            P = build(p, q, m, U, r, NLAYER)
            if len(P) > BMAX or len(P) < 20:
                print(f'  r={r}: {len(P)} points skipped', flush=True)
                continue
            z = np.array([to_z(x, p, q, m) for x in P])
            for t in TS:
                w = complex((2 * t - 1) / (2 * t),
                            math.sqrt(4 * t - 1) / (2 * t))
                Z = np.concatenate([z, z * w])
                seen, keep = set(), []
                for x in Z:
                    key = (round(x.real, 9), round(x.imag, 9))
                    if key not in seen:
                        seen.add(key)
                        keep.append(x)
                Z = np.array(keep)
                if len(Z) > NMAX:
                    continue
                E = edges_of(Z)
                if not E:
                    continue
                t0 = time.time()
                st = colorable(len(Z), E, f'{PART}_{p}_{q}_{m}_{t}')
                if st is False:
                    pickle.dump((p, q, m, t, r, P),
                                open(f'genhit_{p}_{q}_{m}_{t}.pkl', 'wb'))
                    print(f'  *** r={r} t={t}: {len(Z)} vtx {len(E)} edges '
                          f'NOT 4-colorable ({round(time.time()-t0,1)}s)',
                          flush=True)
                elif st is None:
                    print(f'  r={r} t={t}: {len(Z)} vtx unknown', flush=True)
            print(f'  r={r}: base {len(P)} done', flush=True)


if __name__ == '__main__':
    main()
