/* P21 v1: simulated annealing over C7-orbit colorings of K50.
 * State: color[o] in {0..k-1} u {-1 = uncolored} for the 175 sigma-orbits
 * (uncolored allowed only when k<7; for k=7 all orbits colored).
 * Energy: sum over colors of |deg(v,c)-7| over the 8 vertex-orbit reps
 *         + #monochromatic triangle reps + #monochromatic C4 reps.
 * Energy 0 <=> valid k-packing of HoSi copies (each color 7-regular girth>=5).
 * Input files (generated by gen_anneal_input.py): anneal_in.txt
 * Usage: anneal <k> <seed> [out]
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#define NO 175
#define NV 8   /* vertex-orbit representatives */
static int ntri, nc4;
static int (*tri)[3];
static int (*c4o)[4];
static int wdeg[NV][NO];        /* weight of orbit o at vrep v */
/* memberships */
static int *tlist[NO], *tmult[NO], tln[NO];
static int *qlist[NO], *qmult[NO], qln[NO];

static int K;
static int color[NO];
static int deg[NV][8];          /* deg[v][c] total weight colored c */
static int tcnt_[3000][8];
static int qcnt_[96000][8];
static long long energy;

static inline int degpen(int d){ int x = d-7; return x<0?-x:x; }

static long long full_energy(void){
    long long e=0;
    memset(deg,0,sizeof deg); 
    for(int t=0;t<ntri;t++) for(int c=0;c<K;c++) tcnt_[t][c]=0;
    for(int q=0;q<nc4;q++) for(int c=0;c<K;c++) qcnt_[q][c]=0;
    for(int o=0;o<NO;o++){
        int c=color[o]; if(c<0) continue;
        for(int v=0;v<NV;v++) deg[v][c]+=wdeg[v][o];
    }
    for(int t=0;t<ntri;t++){
        for(int i=0;i<3;i++){int c=color[tri[t][i]]; if(c>=0) tcnt_[t][c]++;}
        for(int c=0;c<K;c++) if(tcnt_[t][c]==3) e++;
    }
    for(int q=0;q<nc4;q++){
        for(int i=0;i<4;i++){int c=color[c4o[q][i]]; if(c>=0) qcnt_[q][c]++;}
        for(int c=0;c<K;c++) if(qcnt_[q][c]==4) e++;
    }
    for(int v=0;v<NV;v++) for(int c=0;c<K;c++) e+=degpen(deg[v][c]);
    return e;
}

/* delta of recoloring orbit o from oc to nc (either may be -1) */
static long long delta(int o,int oc,int nc){
    long long d=0;
    for(int v=0;v<NV;v++){
        int w=wdeg[v][o]; if(!w) continue;
        if(oc>=0) d += degpen(deg[v][oc]-w)-degpen(deg[v][oc]);
        if(nc>=0) d += degpen(deg[v][nc]+w)-degpen(deg[v][nc]);
    }
    for(int i=0;i<tln[o];i++){
        int t=tlist[o][i], m=tmult[o][i];
        int b=0,a=0;
        if(oc>=0){ b+=(tcnt_[t][oc]==3); a+=(tcnt_[t][oc]-m==3); }
        if(nc>=0){ b+=(tcnt_[t][nc]==3); a+=(tcnt_[t][nc]+m==3); }
        d += a-b;
    }
    for(int i=0;i<qln[o];i++){
        int q=qlist[o][i], m=qmult[o][i];
        int b=0,a=0;
        if(oc>=0){ b+=(qcnt_[q][oc]==4); a+=(qcnt_[q][oc]-m==4); }
        if(nc>=0){ b+=(qcnt_[q][nc]==4); a+=(qcnt_[q][nc]+m==4); }
        d += a-b;
    }
    return d;
}
static void apply(int o,int oc,int nc){
    for(int v=0;v<NV;v++){
        int w=wdeg[v][o]; if(!w) continue;
        if(oc>=0) deg[v][oc]-=w;
        if(nc>=0) deg[v][nc]+=w;
    }
    for(int i=0;i<tln[o];i++){int t=tlist[o][i],m=tmult[o][i]; if(oc>=0)tcnt_[t][oc]-=m; if(nc>=0)tcnt_[t][nc]+=m;}
    for(int i=0;i<qln[o];i++){int q=qlist[o][i],m=qmult[o][i]; if(oc>=0)qcnt_[q][oc]-=m; if(nc>=0)qcnt_[q][nc]+=m;}
    color[o]=nc;
}

int main(int argc,char**argv){
    K=atoi(argv[1]);
    unsigned seed=atoi(argv[2]);
    srand(seed);
    FILE*f=fopen("anneal_in.txt","r");
    if(!f){fprintf(stderr,"missing anneal_in.txt\n");return 2;}
    fscanf(f,"%d %d",&ntri,&nc4);
    tri=malloc(ntri*sizeof *tri); c4o=malloc(nc4*sizeof *c4o);
    for(int t=0;t<ntri;t++) fscanf(f,"%d %d %d",&tri[t][0],&tri[t][1],&tri[t][2]);
    for(int q=0;q<nc4;q++) fscanf(f,"%d %d %d %d",&c4o[q][0],&c4o[q][1],&c4o[q][2],&c4o[q][3]);
    for(int v=0;v<NV;v++) for(int o=0;o<NO;o++) fscanf(f,"%d",&wdeg[v][o]);
    fclose(f);
    /* memberships, deduped with multiplicities */
    for(int o=0;o<NO;o++){tln[o]=qln[o]=0;}
    for(int t=0;t<ntri;t++) for(int i=0;i<3;i++) tln[tri[t][i]]++;
    for(int q=0;q<nc4;q++) for(int i=0;i<4;i++) qln[c4o[q][i]]++;
    for(int o=0;o<NO;o++){
        tlist[o]=malloc(tln[o]*sizeof(int));tmult[o]=malloc(tln[o]*sizeof(int));
        qlist[o]=malloc(qln[o]*sizeof(int));qmult[o]=malloc(qln[o]*sizeof(int));
        tln[o]=qln[o]=0;
    }
    for(int t=0;t<ntri;t++) for(int i=0;i<3;i++){
        int o=tri[t][i];
        if(i>0 && tri[t][i-1]==o){ tmult[o][tln[o]-1]++; continue; }
        tlist[o][tln[o]]=t; tmult[o][tln[o]]=1; tln[o]++;
    }
    for(int q=0;q<nc4;q++) for(int i=0;i<4;i++){
        int o=c4o[q][i];
        if(i>0 && c4o[q][i-1]==o){ qmult[o][qln[o]-1]++; continue; }
        qlist[o][qln[o]]=q; qmult[o][qln[o]]=1; qln[o]++;
    }
    /* init: random coloring; for k<7, each color gets exactly 25 random orbits */
    int perm[NO]; for(int o=0;o<NO;o++)perm[o]=o;
    for(int i=NO-1;i>0;i--){int j=rand()%(i+1);int t=perm[i];perm[i]=perm[j];perm[j]=t;}
    for(int o=0;o<NO;o++)color[o]=-1;
    for(int c=0;c<K;c++) for(int i=0;i<25;i++) color[perm[c*25+i]]=c;
    energy=full_energy();
    fprintf(stderr,"start energy %lld\n",energy);
    double T=2.0;
    long long best=energy;
    long long iter=0, report=1LL<<23;
    while(energy>0){
        iter++;
        if(!(iter&(report-1))){
            fprintf(stderr,"iter %lld T=%.4f energy %lld best %lld\n",iter,T,energy,best);
            long long chk=full_energy();
            if(chk!=energy){fprintf(stderr,"DRIFT %lld vs %lld\n",energy,chk);energy=chk;}
        }
        T *= 0.99999998; if(T<0.03){T=1.0;} /* reheat cycles */
        int o=rand()%NO;
        int oc=color[o];
        int nc;
        if(K<7){ nc=rand()%(K+1)-1; } else { nc=rand()%K; }
        if(nc==oc) continue;
        long long d=delta(o,oc,nc);
        if(d<=0 || ((double)rand()/RAND_MAX) < exp(-(double)d/T)){
            apply(o,oc,nc);
            energy+=d;
            if(energy<best){best=energy;
                if(best<10)fprintf(stderr,"iter %lld new best %lld\n",iter,best);}
        }
    }
    fprintf(stderr,"SOLVED at iter %lld\n",iter);
    FILE*out=fopen(argc>3?argv[3]:"anneal_out.txt","w");
    for(int o=0;o<NO;o++) fprintf(out,"%d %d\n",o,color[o]);
    fclose(out);
    return 0;
}
