/* P09 Bollobas-Nikiforov: dihedral Cayley graph sweep (round 5).
 *
 * Cayley graphs of the dihedral group D_n (order 2n <= 64), a vertex-transitive
 * family strictly beyond circulants. Group elements: r^i (i<n) and s r^i.
 * Connection set S closed under inversion, S generated by choosing:
 *   - rotation pairs {r^k, r^-k} for 1 <= k < n/2  (bits 0..nh-1)
 *   - r^{n/2} if n even                            (next bit)
 *   - reflections s r^i, each self-inverse         (next n bits)
 * Exhaustive over all 2^(nh + even + n) - trivial sets when feasible,
 * otherwise random sampling. gap = l1^2 + l2^2 - 2m(1-1/w); anything
 * > 1e-7 printed as CANDIDATE (verify independently with verify.py).
 *
 * Usage: ./cayley n [samples seed]   (samples==0 or absent -> exhaustive)
 * Build: gcc -O3 -march=native -o cayley cayley.c -lm
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <stdint.h>

#define MAXV 64
static int N;   /* group order = 2n */
static int n;   /* dihedral parameter */
static double A[MAXV][MAXV];
static uint64_t adj[MAXV];

static void tridiag(int nn, double a[MAXV][MAXV], double *d, double *e) {
    for (int i = nn - 1; i >= 1; i--) {
        int l = i - 1;
        double h = 0.0, scale = 0.0;
        if (l > 0) {
            for (int k = 0; k <= l; k++) scale += fabs(a[i][k]);
            if (scale == 0.0) e[i] = a[i][l];
            else {
                for (int k = 0; k <= l; k++) { a[i][k] /= scale; h += a[i][k] * a[i][k]; }
                double f = a[i][l];
                double g = (f >= 0.0) ? -sqrt(h) : sqrt(h);
                e[i] = scale * g; h -= f * g; a[i][l] = f - g; f = 0.0;
                for (int j = 0; j <= l; j++) {
                    g = 0.0;
                    for (int k = 0; k <= j; k++) g += a[j][k] * a[i][k];
                    for (int k = j + 1; k <= l; k++) g += a[k][j] * a[i][k];
                    e[j] = g / h; f += e[j] * a[i][j];
                }
                double hh = f / (h + h);
                for (int j = 0; j <= l; j++) {
                    f = a[i][j];
                    e[j] = g = e[j] - hh * f;
                    for (int k = 0; k <= j; k++) a[j][k] -= (f * e[k] + g * a[i][k]);
                }
            }
        } else e[i] = a[i][l];
        d[i] = h;
    }
    e[0] = 0.0;
    for (int i = 0; i < nn; i++) d[i] = a[i][i];
}

static int sturm_count(int nn, const double *d, const double *e, double x) {
    int cnt = 0;
    double q = d[0] - x;
    if (q < 0) cnt++;
    for (int i = 1; i < nn; i++) {
        double denom = (q == 0.0) ? 1e-300 : q;
        q = d[i] - x - e[i] * e[i] / denom;
        if (q < 0) cnt++;
    }
    return cnt;
}

static double kth_largest(int nn, const double *d, const double *e, int k, double lo, double hi) {
    for (int it = 0; it < 60; it++) {
        double mid = 0.5 * (lo + hi);
        if (sturm_count(nn, d, e, mid) >= nn - k + 1) hi = mid;
        else lo = mid;
        if (hi - lo < 1e-12) break;
    }
    return 0.5 * (lo + hi);
}

static int best_clique;
static void expand(uint64_t cand, int size) {
    if (!cand) { if (size > best_clique) best_clique = size; return; }
    while (cand) {
        if (size + __builtin_popcountll(cand) <= best_clique) return;
        int v = __builtin_ctzll(cand);
        cand &= cand - 1;
        expand(cand & adj[v], size + 1);
    }
}
static int max_clique(void) {
    best_clique = 1;
    expand((N == 64) ? ~0ull : ((1ull << N) - 1), 0);
    return best_clique;
}

/* element encoding: 0..n-1 = r^i ; n..2n-1 = s r^(i-n) */
static int mul(int a, int b) { /* a*b in D_n */
    int ar = a % n, as = a / n, br = b % n, bs = b / n;
    /* (s^as r^ar)(s^bs r^br) ; r s = s r^-1 => r^ar s = s r^(-ar) */
    int rs, rr;
    if (bs == 0) { rs = as; rr = (ar + br) % n; }
    else { rs = 1 - as; rr = ((br - ar) % n + n) % n; }
    return rs * n + rr;
}

static long long checked = 0, cands = 0;
static double best_gap = -1e18;
static char best_desc[256] = "";

static void eval_set(const int *S, int slen, const char *desc) {
    memset(A, 0, sizeof A);
    memset(adj, 0, sizeof adj);
    int m = 0;
    for (int g = 0; g < N; g++)
        for (int t = 0; t < slen; t++) {
            int hgt = mul(g, S[t]);
            if (!(adj[g] >> hgt & 1)) {
                adj[g] |= 1ull << hgt; adj[hgt] |= 1ull << g;
                A[g][hgt] = A[hgt][g] = 1.0;
            }
        }
    for (int i = 0; i < N; i++) m += __builtin_popcountll(adj[i]);
    m /= 2;
    if (m == 0 || m == N * (N - 1) / 2) return;
    static double T[MAXV][MAXV];
    memcpy(T, A, sizeof T);
    double d[MAXV], e[MAXV];
    tridiag(N, T, d, e);
    double bound = sqrt(2.0 * m) + 1.0;
    double l1 = kth_largest(N, d, e, 1, -bound, bound);
    double l2 = kth_largest(N, d, e, 2, -bound, l1 + 1e-9);
    double s = l1 * l1 + l2 * l2;
    if (s <= (double)m - 1e-6) { checked++; return; } /* rhs >= m always */
    int w = max_clique();
    double rhs = 2.0 * m * (1.0 - 1.0 / w);
    double gap = s - rhs;
    checked++;
    if (gap > best_gap) { best_gap = gap; snprintf(best_desc, 255, "n=%d m=%d w=%d l1=%.9f l2=%.9f %s", n, m, w, l1, l2, desc); }
    if (gap > 1e-7) {
        cands++;
        printf("CANDIDATE dihedral n=%d m=%d w=%d l1=%.12f l2=%.12f gap=%.3e set=%s\n",
               n, m, w, l1, l2, gap, desc);
        fflush(stdout);
    }
}

static unsigned long long rs_;
static double rnd(void) {
    rs_ ^= rs_ << 13; rs_ ^= rs_ >> 7; rs_ ^= rs_ << 17;
    return (double)(rs_ >> 11) / 9007199254740992.0;
}

int main(int argc, char **argv) {
    if (argc < 2) { fprintf(stderr, "usage: %s n [samples seed]\n", argv[0]); return 1; }
    n = atoi(argv[1]);
    N = 2 * n;
    if (N > MAXV) { fprintf(stderr, "2n > 64\n"); return 1; }
    long long samples = argc > 2 ? atoll(argv[2]) : 0;
    rs_ = (argc > 3 ? strtoull(argv[3], 0, 10) : 1) * 2654435761ull + 88172645463325252ull;

    int nh = (n - 1) / 2;          /* rotation pairs r^k, 1<=k<=nh */
    int has_half = (n % 2 == 0);   /* r^{n/2} */
    int nbits = nh + has_half + n; /* + n reflections */
    int S[3 * MAXV]; char desc[256];

    if (samples == 0 && nbits <= 26) {
        long long tot = 1ll << nbits;
        for (long long mask = 1; mask < tot; mask++) {
            int slen = 0;
            for (int k = 1; k <= nh; k++)
                if (mask >> (k - 1) & 1) { S[slen++] = k; S[slen++] = n - k; }
            if (has_half && (mask >> nh & 1)) S[slen++] = n / 2;
            for (int i = 0; i < n; i++)
                if (mask >> (nh + has_half + i) & 1) S[slen++] = n + i;
            snprintf(desc, 255, "mask=%llx", mask);
            eval_set(S, slen, desc);
        }
    } else {
        if (samples == 0) samples = 20000000;
        for (long long it = 0; it < samples; it++) {
            int slen = 0;
            double p = 0.1 + 0.8 * rnd();
            unsigned long long mask = 0;
            for (int b = 0; b < nbits; b++) if (rnd() < p) mask |= 1ull << b;
            if (!mask) continue;
            for (int k = 1; k <= nh; k++)
                if (mask >> (k - 1) & 1) { S[slen++] = k; S[slen++] = n - k; }
            if (has_half && (mask >> nh & 1)) S[slen++] = n / 2;
            for (int i = 0; i < n; i++)
                if (mask >> (nh + has_half + i) & 1) S[slen++] = n + i;
            snprintf(desc, 255, "mask=%llx", mask);
            eval_set(S, slen, desc);
        }
    }
    fprintf(stderr, "CAYLEY-SUMMARY n=%d order=%d checked=%lld candidates=%lld best_gap=%.6e best=[%s]\n",
            n, N, checked, cands, best_gap, best_desc);
    return 0;
}
