"""Rotated-copy pool: G509 union exact rotations R_k(G509) about the origin,
R in the group generated by u1 = 5/6 + (sqrt11/6) i and u2 = 1/2 + (sqrt3/2) i
(both exact unit rotations in Q(sqrt3,sqrt5,sqrt11)). Rotation of (x,y) by
(a,b): (ax - by, bx + ay). Output: pool_rot.pkl (G509 first) + rot_idx.pkl.
"""
import pickle
from fractions import Fraction as F
import numpy as np
from field import add, sub, mul, to_float, norm2, ONE, N

def fe(*pairs):
    t = [F(0)] * N
    for idx, val in pairs:
        t[idx] = F(val)
    return tuple(t)

# basis order: 1, r3, r5, r15, r11, r33, r55, r165 (masks 0..7 by _radval)
A1, B1 = fe((0, F(5, 6))), fe((4, F(1, 6)))      # 5/6, sqrt11/6
A2, B2 = fe((0, F(1, 2))), fe((1, F(1, 2)))      # 1/2, sqrt3/2

def rot(p, a, b):
    x, y = p
    return (sub(mul(a, x), mul(b, y)), add(mul(b, x), mul(a, y)))

def compose(r1, r2):
    a1, b1 = r1; a2, b2 = r2
    return (sub(mul(a1, a2), mul(b1, b2)), add(mul(a1, b2), mul(b1, a2)))

pts509 = pickle.load(open('g509.pkl', 'rb'))[0]
base = [(A1, B1), (A2, B2), compose((A1, B1), (A2, B2)),
        compose((A1, B1), (A1, B1)), compose((A2, B2), (A1, B1))]
seen = dict((p, i) for i, p in enumerate(pts509))
allp = list(pts509)
for a, b in base:
    for p in pts509:
        q = rot(p, a, b)
        if q not in seen:
            seen[q] = len(allp)
            allp.append(q)
print('pool with rotated copies:', len(allp))

Af = np.array([(to_float(p[0]), to_float(p[1])) for p in allp])
E = []
CH = 1500
for s in range(0, len(allp), CH):
    d2 = ((Af[s:s+CH, None, :] - Af[None, :, :]) ** 2).sum(-1)
    ii, jj = np.nonzero(np.abs(d2 - 1.0) < 1e-6)
    for a, b in zip(ii, jj):
        ga, gb = s + a, b
        if ga < gb and norm2(allp[ga], allp[gb]) == ONE:
            E.append((ga, gb))
pickle.dump((allp, E), open('pool_rot.pkl', 'wb'))
print('FINAL rotated pool:', len(allp), 'vertices,', len(E), 'edges')
